import java.io.File
import java.util.jar.JarFile
import java.util.jar.Manifest
import org.gradle.api.GradleException

// Seven classes differ from XStream 1.4.21, all generated by XStream.java and
// Types.java. Compile those two recovered source units and overlay their output
// on the verified upstream JAR so unrelated classes and resources remain exact.
plugins {
    java
}

layout.buildDirectory.set(rootProject.layout.buildDirectory.dir("module-builds/xstream-1.4.21_miko"))

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

val upstream by configurations.creating {
    isTransitive = false
}

val allowedOverlayEntries = setOf(
    "com/thoughtworks/xstream/XStream.class",
    "com/thoughtworks/xstream/XStream\$1.class",
    "com/thoughtworks/xstream/XStream\$2.class",
    "com/thoughtworks/xstream/XStream\$3.class",
    "com/thoughtworks/xstream/XStream\$4.class",
    "com/thoughtworks/xstream/XStream\$InitializationException.class",
    "com/thoughtworks/xstream/core/util/Types.class",
)

fun compiledOverlayEntries(): Set<String> = sourceSets.main.get().output.classesDirs.files
    .filter(File::exists)
    .flatMap { root ->
        root.walkTopDown()
            .filter { it.isFile && it.extension == "class" }
            .map { it.relativeTo(root).path.replace(File.separatorChar, '/') }
            .toList()
    }
    .toSortedSet()

dependencies {
    upstream("com.thoughtworks.xstream:xstream:1.4.21")
    compileOnly("com.thoughtworks.xstream:xstream:1.4.21")
    compileOnly("io.github.x-stream:mxparser:1.2.2")
    compileOnly("xpp3:xpp3_min:1.1.4c")
}

sourceSets {
    main {
        java.setSrcDirs(listOf("."))
        java.include(
            "com/thoughtworks/xstream/XStream.java",
            "com/thoughtworks/xstream/core/util/Types.java",
        )
        resources.setSrcDirs(emptyList<String>())
    }
}

tasks.named<JavaCompile>("compileJava") {
    options.encoding = "UTF-8"
}

val validateOverlayAssembly by tasks.registering {
    group = "verification"
    description = "Fails if the XStream overlay compiles or replaces anything beyond the intended XStream and Types classes."
    dependsOn(tasks.named("classes"))
    inputs.files(sourceSets.main.get().output.classesDirs)
    inputs.file(provider { upstream.singleFile })
    inputs.file(layout.projectDirectory.file("META-INF/MANIFEST.MF"))
    doLast {
        val compiledEntries = compiledOverlayEntries()
        val unexpectedEntries = compiledEntries - allowedOverlayEntries
        val missingEntries = allowedOverlayEntries - compiledEntries
        require(unexpectedEntries.isEmpty() && missingEntries.isEmpty()) {
            "Unexpected XStream overlay classes. Missing=$missingEntries, unexpected=$unexpectedEntries"
        }
        JarFile(upstream.singleFile).use { upstreamJar ->
            val upstreamEntries = upstreamJar.entries().asSequence().map { it.name }.toSet()
            val absentFromUpstream = allowedOverlayEntries - upstreamEntries
            if (absentFromUpstream.isNotEmpty()) {
                throw GradleException("Upstream XStream jar is missing overlay targets: $absentFromUpstream")
            }
            val upstreamManifest = upstreamJar.manifest
                ?: throw GradleException("Upstream XStream jar is missing META-INF/MANIFEST.MF")
            val localManifest = layout.projectDirectory.file("META-INF/MANIFEST.MF").asFile
                .inputStream().use(::Manifest)
            if (upstreamManifest.mainAttributes != localManifest.mainAttributes ||
                upstreamManifest.entries != localManifest.entries
            ) {
                throw GradleException("Recovered XStream manifest diverges from the upstream jar manifest.")
            }
        }
    }
}

tasks.named<Jar>("jar") {
    dependsOn(validateOverlayAssembly)
    archiveBaseName.set("xstream")
    archiveVersion.set("")
    archiveFileName.set("xstream-1.4.21_miko.jar")
    duplicatesStrategy = DuplicatesStrategy.FAIL
    from({
        zipTree(upstream.singleFile)
    }) {
        exclude(
            *allowedOverlayEntries.toTypedArray(),
            "META-INF/MANIFEST.MF",
        )
    }
    manifest.from("META-INF/MANIFEST.MF")
}
