FastRenderingReleasesUrl=https://github.com/Halke1986/starsector-render/releases
FastRenderingLinuxReleasesUrl=https://github.com/jontyab/starsector-render/releases/tag/v0.8.7-port-78c1c903
ResourceCacheReleasesUrl=https://github.com/GaiusCassiusL/Starsector_FR-Resource-Cache
ResourceCacheLatestReleaseApi=https://api.github.com/repos/GaiusCassiusL/Starsector_FR-Resource-Cache/releases/latest
ResourceCacheAssetUrlPrefix=https://github.com/GaiusCassiusL/Starsector_FR-Resource-Cache/releases/download/
PrepatcherReleasesUrl=https://github.com/cyrrp/StarsectorPrepatcher/releases
VramOptimizerReleasesUrl=https://github.com/DeCEll-1/VramOptimizer
MinimumPrepatcherVersion=0.18.4
